const mathematicsCourses = [
  // ===== 100 LEVEL — FIRST SEMESTER (total 17) =====
  {
    courseCode: 'GST111',
    title: 'Communication in English',
    unit: 2,
    level: 100,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'EDU101',
    title: 'Introduction to Teaching and Foundations of Education',
    unit: 2,
    level: 100,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'MTH101',
    title: 'Elementary Mathematics I',
    unit: 2,
    level: 100,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'PHY101',
    title: 'General Physics I',
    unit: 2,
    level: 100,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'COS101',
    title: 'Computer Programming Language I',
    unit: 3,
    level: 100,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED175',
    title: 'Elementary Mechanics I',
    unit: 2,
    level: 100,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-EDU101',
    title: 'Sociological Foundations of Education',
    unit: 2,
    level: 100,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-GST113',
    title: 'Humanities',
    unit: 2,
    level: 100,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-GST115',
    title: 'Communication Skills',
    unit: 0,
    level: 100,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },

  // ===== 100 LEVEL — SECOND SEMESTER (total 16) =====
  {
    courseCode: 'GST112',
    title: 'Nigerian Peoples and Culture',
    unit: 2,
    level: 100,
    semester: 2,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'MTH102',
    title: 'Elementary Mathematics II',
    unit: 2,
    level: 100,
    semester: 2,
    department: 'Mathematics',
    prerequisites: ['MTH101'],
  },
  {
    courseCode: 'PHY102',
    title: 'General Physics II',
    unit: 2,
    level: 100,
    semester: 2,
    department: 'Mathematics',
    prerequisites: ['PHY101'],
  },
  {
    courseCode: 'NAU-EDU112',
    title: 'Introduction to Educational Psychology',
    unit: 2,
    level: 100,
    semester: 2,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-GST114',
    title: 'Basic Igbo Studies',
    unit: 2,
    level: 100,
    semester: 2,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED176',
    title: 'Elementary Mechanics II',
    unit: 2,
    level: 100,
    semester: 2,
    department: 'Mathematics',
    prerequisites: ['NAU-SED175'],
  },
  {
    courseCode: 'NAU-SED164',
    title: 'Introduction to Actuarial Mathematics I',
    unit: 2,
    level: 100,
    semester: 2,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED152',
    title: 'History and Philosophy of Science',
    unit: 2,
    level: 100,
    semester: 2,
    department: 'Mathematics',
    prerequisites: [],
  },

  // ===== 200 LEVEL — FIRST SEMESTER (total 17) =====
  {
    courseCode: 'SED101',
    title: 'Introduction to Science and Mathematics Education',
    unit: 2,
    level: 200,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'MTH161',
    title: 'Elementary Mathematics III',
    unit: 2,
    level: 200,
    semester: 1,
    department: 'Mathematics',
    prerequisites: ['MTH101'],
  },
  {
    courseCode: 'ENT211',
    title: 'Entrepreneurship and Innovation',
    unit: 2,
    level: 200,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'EDU201',
    title: 'Curriculum Delivery and General Teaching Methods',
    unit: 2,
    level: 200,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'MTH201',
    title: 'Linear Algebra I',
    unit: 2,
    level: 200,
    semester: 1,
    department: 'Mathematics',
    prerequisites: ['MTH102'],
  },
  {
    courseCode: 'MTH251',
    title: 'Real Analysis I',
    unit: 2,
    level: 200,
    semester: 1,
    department: 'Mathematics',
    prerequisites: ['MTH102'],
  },
  {
    courseCode: 'NAU-SED161',
    title: 'Probability I',
    unit: 2,
    level: 200,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED165',
    title: 'Mathematics Laboratory Practical',
    unit: 1,
    level: 200,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-EDU211',
    title: 'Human Learning and Instruction in Digital Age',
    unit: 2,
    level: 200,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },

  // ===== 200 LEVEL — SECOND SEMESTER (total 17) =====
  {
    courseCode: 'COS102',
    title: 'Computer Programming Language II',
    unit: 3,
    level: 200,
    semester: 2,
    department: 'Mathematics',
    prerequisites: ['COS101'],
  },
  {
    courseCode: 'GST212',
    title: 'Philosophy, Logic and Human Existence',
    unit: 2,
    level: 200,
    semester: 2,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'MTH202',
    title: 'Elementary Differential Equations',
    unit: 2,
    level: 200,
    semester: 2,
    department: 'Mathematics',
    prerequisites: ['MTH102'],
  },
  {
    courseCode: 'MTH204',
    title: 'Linear Algebra II',
    unit: 2,
    level: 200,
    semester: 2,
    department: 'Mathematics',
    prerequisites: ['MTH201'],
  },
  {
    courseCode: 'MTH222',
    title: 'Introduction to Numerical Analysis',
    unit: 2,
    level: 200,
    semester: 2,
    department: 'Mathematics',
    prerequisites: ['MTH102'],
  },
  {
    courseCode: 'CDS200',
    title: 'Career Development Studies',
    unit: 0,
    level: 200,
    semester: 2,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED166',
    title: 'Special Projects in Mathematics Education',
    unit: 2,
    level: 200,
    semester: 2,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED168',
    title: 'Probability II',
    unit: 2,
    level: 200,
    semester: 2,
    department: 'Mathematics',
    prerequisites: ['NAU-SED161'],
  },
  {
    courseCode: 'NAU-EDU216',
    title: 'Digital Technologies for Curriculum Delivery',
    unit: 2,
    level: 200,
    semester: 2,
    department: 'Mathematics',
    prerequisites: [],
  },

  // ===== 300 LEVEL — FIRST SEMESTER (total 18) =====
  {
    courseCode: 'COS201',
    title: 'Computer Programming I',
    unit: 3,
    level: 300,
    semester: 1,
    department: 'Mathematics',
    prerequisites: ['COS102'],
  },
  {
    courseCode: 'MTH231',
    title: 'Introduction to Mathematical Methods I',
    unit: 2,
    level: 300,
    semester: 1,
    department: 'Mathematics',
    prerequisites: ['MTH102'],
  },
  {
    courseCode: 'MTH241',
    title: 'Algebra of Sets and Symbolic Logic',
    unit: 2,
    level: 300,
    semester: 1,
    department: 'Mathematics',
    prerequisites: ['MTH102'],
  },
  {
    courseCode: 'MTH353',
    title: 'Metric Space Topology',
    unit: 3,
    level: 300,
    semester: 1,
    department: 'Mathematics',
    prerequisites: ['MTH251'],
  },
  {
    courseCode: 'NAU-SED265',
    title: 'Introduction to Actuarial Mathematics II',
    unit: 2,
    level: 300,
    semester: 1,
    department: 'Mathematics',
    prerequisites: ['NAU-SED164'],
  },
  {
    courseCode: 'NAU-SED257',
    title: 'General Science Education Laboratory',
    unit: 2,
    level: 300,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED351',
    title: 'Laboratory Organization and Management',
    unit: 2,
    level: 300,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED251',
    title: 'Introduction to Science Education',
    unit: 2,
    level: 300,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },

  // ===== 300 LEVEL — SECOND SEMESTER (total 16) =====
  {
    courseCode: 'GST312',
    title: 'Peace and Conflict Resolution',
    unit: 2,
    level: 300,
    semester: 2,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'ENT312',
    title: 'Venture Creation',
    unit: 2,
    level: 300,
    semester: 2,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'MTH332',
    title: 'Ordinary Differential Equations',
    unit: 2,
    level: 300,
    semester: 2,
    department: 'Mathematics',
    prerequisites: ['MTH202'],
  },
  {
    courseCode: 'SED302',
    title: 'Methods of Mathematics Teaching',
    unit: 2,
    level: 300,
    semester: 2,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED262',
    title: 'Operational Research',
    unit: 2,
    level: 300,
    semester: 2,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED264',
    title: 'Introduction to Geometry',
    unit: 2,
    level: 300,
    semester: 2,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED268',
    title: 'Problem Solving in Secondary School Mathematics',
    unit: 2,
    level: 300,
    semester: 2,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-EDU212',
    title: 'Micro Teaching Practice',
    unit: 2,
    level: 300,
    semester: 2,
    department: 'Mathematics',
    prerequisites: [],
  },

  // ===== 400 LEVEL — FIRST SEMESTER (total 17) — exempt from 15 min =====
  {
    courseCode: 'MTH361',
    title: 'Vector and Tensor Analysis',
    unit: 2,
    level: 400,
    semester: 1,
    department: 'Mathematics',
    prerequisites: ['MTH202'],
  },
  {
    courseCode: 'MTH355',
    title: 'Complex Analysis I',
    unit: 2,
    level: 400,
    semester: 1,
    department: 'Mathematics',
    prerequisites: ['MTH251'],
  },
  {
    courseCode: 'MTH351',
    title: 'Real Analysis II',
    unit: 2,
    level: 400,
    semester: 1,
    department: 'Mathematics',
    prerequisites: ['MTH251'],
  },
  {
    courseCode: 'SED303',
    title: 'Entrepreneurship in Mathematics Education',
    unit: 2,
    level: 400,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'EDU302',
    title: 'Educational Measurements, Tests, Research Methods and Statistics',
    unit: 3,
    level: 400,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'MTH341',
    title: 'Abstract Algebra I',
    unit: 2,
    level: 400,
    semester: 1,
    department: 'Mathematics',
    prerequisites: ['MTH241'],
  },
  {
    courseCode: 'NAU-SED353',
    title: 'Seminar, Grant and Project Writing in Science Education',
    unit: 2,
    level: 400,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-EDU335',
    title: 'Introduction to Special Needs Education',
    unit: 2,
    level: 400,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },

  // ===== 400 LEVEL — SECOND SEMESTER (total 6) — exempt (practicum) =====
  {
    courseCode: 'EDU326',
    title: 'Teaching Practice II',
    unit: 6,
    level: 400,
    semester: 2,
    department: 'Mathematics',
    prerequisites: [],
  },

  // ===== 500 LEVEL — FIRST SEMESTER (total 15) =====
  {
    courseCode: 'MTH431',
    title: 'Theory of Ordinary Differential Equations',
    unit: 3,
    level: 500,
    semester: 1,
    department: 'Mathematics',
    prerequisites: ['MTH332'],
  },
  {
    courseCode: 'MTH433',
    title: 'Mathematical Methods II',
    unit: 3,
    level: 500,
    semester: 1,
    department: 'Mathematics',
    prerequisites: ['MTH231'],
  },
  {
    courseCode: 'MTH451',
    title: 'General Topology',
    unit: 3,
    level: 500,
    semester: 1,
    department: 'Mathematics',
    prerequisites: ['MTH353'],
  },
  {
    courseCode: 'NAU-SED451',
    title: 'Special Problems in Science Education',
    unit: 2,
    level: 500,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED453',
    title: 'Integrating Science',
    unit: 2,
    level: 500,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED465',
    title: 'Sets, Logic and Algebra',
    unit: 2,
    level: 500,
    semester: 1,
    department: 'Mathematics',
    prerequisites: [],
  },

  // ===== 500 LEVEL — SECOND SEMESTER (total 16) =====
  {
    courseCode: 'MTH342',
    title: 'Abstract Algebra II',
    unit: 2,
    level: 500,
    semester: 2,
    department: 'Mathematics',
    prerequisites: ['MTH341'],
  },
  {
    courseCode: 'MTH356',
    title: 'Complex Analysis II',
    unit: 2,
    level: 500,
    semester: 2,
    department: 'Mathematics',
    prerequisites: ['MTH355'],
  },
  {
    courseCode: 'EDU400',
    title: 'Project',
    unit: 3,
    level: 500,
    semester: 2,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'MTH422',
    title: 'Mathematical Modelling',
    unit: 2,
    level: 500,
    semester: 2,
    department: 'Mathematics',
    prerequisites: ['MTH332'],
  },
  {
    courseCode: 'MTH452',
    title: 'Functional Analysis',
    unit: 3,
    level: 500,
    semester: 2,
    department: 'Mathematics',
    prerequisites: ['MTH351'],
  },
  {
    courseCode: 'MTH432',
    title: 'Theory of Partial Differential Equations',
    unit: 2,
    level: 500,
    semester: 2,
    department: 'Mathematics',
    prerequisites: ['MTH332'],
  },
  {
    courseCode: 'CDS400',
    title: 'Career Development Studies',
    unit: 0,
    level: 500,
    semester: 2,
    department: 'Mathematics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED452',
    title: 'Curriculum Development in Science Education',
    unit: 2,
    level: 500,
    semester: 2,
    department: 'Mathematics',
    prerequisites: [],
  },
];

module.exports = mathematicsCourses;
