// seed/courses.cs.js
// Computer Science curriculum (Years 1-5), cleaned from the course document.
// dept = "Computer Science" on every record. Direct Entry tables excluded.

const computerScienceCourses = [
  // ===== 100 LEVEL — FIRST SEMESTER (total 18) =====
  {
    courseCode: 'COS101',
    title: 'Introduction to Computer Science',
    unit: 3,
    level: 100,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'GST111',
    title: 'Communication in English',
    unit: 2,
    level: 100,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'EDU101',
    title: 'Introduction to Teaching and Foundations of Education',
    unit: 2,
    level: 100,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'MTH101',
    title: 'Elementary Mathematics I',
    unit: 2,
    level: 100,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'PHY101',
    title: 'General Physics I',
    unit: 2,
    level: 100,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'PHY107',
    title: 'General Physics Practical I',
    unit: 1,
    level: 100,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'CHM101',
    title: 'General Chemistry I (Inorganic)',
    unit: 2,
    level: 100,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-GST113',
    title: 'Humanities',
    unit: 2,
    level: 100,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-GST115',
    title: 'Communication Skills',
    unit: 0,
    level: 100,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-EDU101',
    title: 'Sociological Foundations of Education',
    unit: 2,
    level: 100,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },

  // ===== 100 LEVEL — SECOND SEMESTER (total 18) =====
  {
    courseCode: 'COS102',
    title: 'Problem Solving',
    unit: 3,
    level: 100,
    semester: 2,
    department: 'Computer Science',
    prerequisites: ['COS101'],
  },
  {
    courseCode: 'MTH102',
    title: 'General Mathematics II',
    unit: 2,
    level: 100,
    semester: 2,
    department: 'Computer Science',
    prerequisites: ['MTH101'],
  },
  {
    courseCode: 'GST112',
    title: 'Nigerian Peoples and Culture',
    unit: 2,
    level: 100,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'CHM102',
    title: 'General Chemistry II (Organic)',
    unit: 2,
    level: 100,
    semester: 2,
    department: 'Computer Science',
    prerequisites: ['CHM101'],
  },
  {
    courseCode: 'PHY102',
    title: 'General Physics II',
    unit: 2,
    level: 100,
    semester: 2,
    department: 'Computer Science',
    prerequisites: ['PHY101'],
  },
  {
    courseCode: 'PHY108',
    title: 'General Physics Practical II',
    unit: 1,
    level: 100,
    semester: 2,
    department: 'Computer Science',
    prerequisites: ['PHY107'],
  },
  {
    courseCode: 'NAU-SED152',
    title: 'History and Philosophy of Science',
    unit: 2,
    level: 100,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-GST114',
    title: 'Basic Igbo Studies',
    unit: 2,
    level: 100,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED132',
    title: 'Basic Computer Appreciation',
    unit: 2,
    level: 100,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },

  // ===== 200 LEVEL — FIRST SEMESTER (total 17) =====
  {
    courseCode: 'COS201',
    title: 'Computer Programming I',
    unit: 3,
    level: 200,
    semester: 1,
    department: 'Computer Science',
    prerequisites: ['COS102'],
  },
  {
    courseCode: 'MTH201',
    title: 'Mathematical Methods I',
    unit: 2,
    level: 200,
    semester: 1,
    department: 'Computer Science',
    prerequisites: ['MTH102'],
  },
  {
    courseCode: 'EDU201',
    title: 'Curriculum Delivery and General Teaching Methods',
    unit: 2,
    level: 200,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED131',
    title: 'Introduction to Computer Education',
    unit: 2,
    level: 200,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED133',
    title: 'Introduction to Operations Research',
    unit: 2,
    level: 200,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED135',
    title: 'Information Management and Communication Technology',
    unit: 2,
    level: 200,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-EDU211',
    title: 'Human Learning and Instruction in Digital Age',
    unit: 2,
    level: 200,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED251',
    title: 'Introduction to Science Education',
    unit: 2,
    level: 200,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },

  // ===== 200 LEVEL — SECOND SEMESTER (total 18) =====
  {
    courseCode: 'COS202',
    title: 'Computer Programming II',
    unit: 3,
    level: 200,
    semester: 2,
    department: 'Computer Science',
    prerequisites: ['COS201'],
  },
  {
    courseCode: 'GST212',
    title: 'Philosophy, Logic and Human Existence',
    unit: 2,
    level: 200,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'MTH202',
    title: 'Mathematical Methods II',
    unit: 2,
    level: 200,
    semester: 2,
    department: 'Computer Science',
    prerequisites: ['MTH201'],
  },
  {
    courseCode: 'CDS200',
    title: 'Career Development Studies',
    unit: 0,
    level: 200,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-EDU112',
    title: 'Introduction to Educational Psychology',
    unit: 2,
    level: 200,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-EDU216',
    title: 'Digital Technologies for Curriculum Delivery',
    unit: 2,
    level: 200,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED134',
    title: 'Special Projects in Computer Education',
    unit: 2,
    level: 200,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED136',
    title: 'Internet and Web Technology',
    unit: 2,
    level: 200,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'COS299',
    title: 'SIWES I',
    unit: 3,
    level: 200,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },

  // ===== 300 LEVEL — FIRST SEMESTER (total 15 after top-up) =====
  {
    courseCode: 'ENT211',
    title: 'Entrepreneurship and Innovation',
    unit: 2,
    level: 300,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'IFT211',
    title: 'Digital Logic Design',
    unit: 2,
    level: 300,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'COS203',
    title: 'Discrete Structures',
    unit: 3,
    level: 300,
    semester: 1,
    department: 'Computer Science',
    prerequisites: ['COS202'],
  },
  {
    courseCode: 'SEN201',
    title: 'Introduction to Software Engineering',
    unit: 2,
    level: 300,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'CYB201',
    title: 'Introduction to Cyber Security and Strategy',
    unit: 2,
    level: 300,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED257',
    title: 'General Science Education Laboratory',
    unit: 2,
    level: 300,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED351',
    title: 'Laboratory Organization and Management',
    unit: 2,
    level: 300,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },

  // ===== 300 LEVEL — SECOND SEMESTER (total 15) =====
  {
    courseCode: 'IFT212',
    title: 'Computer Architecture and Organization',
    unit: 2,
    level: 300,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'ENT312',
    title: 'Venture Creation',
    unit: 2,
    level: 300,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'GST312',
    title: 'Peace and Conflict Resolution',
    unit: 2,
    level: 300,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-EDU212',
    title: 'Micro Teaching Practice',
    unit: 2,
    level: 300,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'DTS304',
    title: 'Data Management',
    unit: 3,
    level: 300,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED234',
    title: 'Information Systems and Management',
    unit: 2,
    level: 300,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED232',
    title: 'General Computer Science Methods',
    unit: 2,
    level: 300,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },

  // ===== 400 LEVEL — FIRST SEMESTER (total 17) — exempt from 15 min =====
  {
    courseCode: 'COS301',
    title: 'Data Structures',
    unit: 3,
    level: 400,
    semester: 1,
    department: 'Computer Science',
    prerequisites: ['COS203'],
  },
  {
    courseCode: 'COS309',
    title: 'Artificial Intelligence',
    unit: 2,
    level: 400,
    semester: 1,
    department: 'Computer Science',
    prerequisites: ['COS203'],
  },
  {
    courseCode: 'EDU302',
    title: 'Educational Measurements, Tests, Research Methods and Statistics',
    unit: 3,
    level: 400,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'ICT305',
    title: 'Data Communication System and Network',
    unit: 3,
    level: 400,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED353',
    title: 'Seminar, Grant and Project Writing in Science Education',
    unit: 2,
    level: 400,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-EDU335',
    title: 'Introduction to Special Needs Education',
    unit: 2,
    level: 400,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED231',
    title: 'Operations Research',
    unit: 2,
    level: 400,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },

  // ===== 400 LEVEL — SECOND SEMESTER (total 6) — exempt (practicum) =====
  {
    courseCode: 'EDU326',
    title: 'Teaching Practice II',
    unit: 3,
    level: 400,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'COS399',
    title: 'SIWES II',
    unit: 3,
    level: 400,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },

  // ===== 500 LEVEL — FIRST SEMESTER (total 16) =====
  {
    courseCode: 'COS401',
    title: 'Algorithms and Complexity Analysis',
    unit: 2,
    level: 500,
    semester: 1,
    department: 'Computer Science',
    prerequisites: ['COS301'],
  },
  {
    courseCode: 'INS401',
    title: 'Project Management',
    unit: 2,
    level: 500,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED431',
    title: 'Data Structures and Algorithms',
    unit: 2,
    level: 500,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED433',
    title: 'Technology and Distance Learning',
    unit: 2,
    level: 500,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED435',
    title: 'Database Management Studies',
    unit: 2,
    level: 500,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED437',
    title: 'Entrepreneurship in Computer Science Education',
    unit: 2,
    level: 500,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED451',
    title: 'Special Problems in Science Education',
    unit: 2,
    level: 500,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED453',
    title: 'Integrating Science',
    unit: 2,
    level: 500,
    semester: 1,
    department: 'Computer Science',
    prerequisites: [],
  },

  // ===== 500 LEVEL — SECOND SEMESTER (total 16) =====
  {
    courseCode: 'COS308',
    title: 'Operating Systems',
    unit: 3,
    level: 500,
    semester: 2,
    department: 'Computer Science',
    prerequisites: ['COS401'],
  },
  {
    courseCode: 'EDU400',
    title: 'Project',
    unit: 3,
    level: 500,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'COS402',
    title: 'Ethics and Legal Issues in Computer Science',
    unit: 2,
    level: 500,
    semester: 2,
    department: 'Computer Science',
    prerequisites: ['COS401'],
  },
  {
    courseCode: 'CDS400',
    title: 'Career Development Studies',
    unit: 0,
    level: 500,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED432',
    title: 'Computer and Society',
    unit: 2,
    level: 500,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED434',
    title: 'Computer Professional Practice and Ethics',
    unit: 2,
    level: 500,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED452',
    title: 'Curriculum Development in Science Education',
    unit: 2,
    level: 500,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED476',
    title: 'Fundamentals of Nanotechnology',
    unit: 2,
    level: 500,
    semester: 2,
    department: 'Computer Science',
    prerequisites: [],
  },
];

module.exports = computerScienceCourses;
