const physicsCourses = [
  // ===== 100 LEVEL — FIRST SEMESTER (total 18) =====
  {
    courseCode: 'GST111',
    title: 'Communication in English',
    unit: 2,
    level: 100,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'COS101',
    title: 'Introduction to Computer Science',
    unit: 3,
    level: 100,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'EDU101',
    title: 'Introduction to Teaching and Foundations of Education',
    unit: 2,
    level: 100,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'MTH101',
    title: 'Elementary Mathematics I',
    unit: 2,
    level: 100,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'PHY101',
    title: 'General Physics I',
    unit: 2,
    level: 100,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'PHY103',
    title: 'General Physics III',
    unit: 2,
    level: 100,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'PHY107',
    title: 'General Physics Practical I',
    unit: 1,
    level: 100,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-GST113',
    title: 'Humanities',
    unit: 2,
    level: 100,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-GST115',
    title: 'Communication Skills',
    unit: 0,
    level: 100,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-EDU101',
    title: 'Sociological Foundations of Education',
    unit: 2,
    level: 100,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },

  // ===== 100 LEVEL — SECOND SEMESTER (total 18) =====
  {
    courseCode: 'GST112',
    title: 'Nigerian Peoples and Culture',
    unit: 2,
    level: 100,
    semester: 2,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'CHM102',
    title: 'General Chemistry II (Organic)',
    unit: 2,
    level: 100,
    semester: 2,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'MTH102',
    title: 'Elementary Mathematics II (Calculus)',
    unit: 2,
    level: 100,
    semester: 2,
    department: 'Physics',
    prerequisites: ['MTH101'],
  },
  {
    courseCode: 'PHY102',
    title: 'General Physics II',
    unit: 2,
    level: 100,
    semester: 2,
    department: 'Physics',
    prerequisites: ['PHY101'],
  },
  {
    courseCode: 'COS102',
    title: 'Problem Solving',
    unit: 3,
    level: 100,
    semester: 2,
    department: 'Physics',
    prerequisites: ['COS101'],
  },
  {
    courseCode: 'PHY108',
    title: 'General Physics Practical II',
    unit: 1,
    level: 100,
    semester: 2,
    department: 'Physics',
    prerequisites: ['PHY107'],
  },
  {
    courseCode: 'PHY104',
    title: 'General Physics IV',
    unit: 2,
    level: 100,
    semester: 2,
    department: 'Physics',
    prerequisites: ['PHY101'],
  },
  {
    courseCode: 'NAU-GST114',
    title: 'Basic Igbo Studies',
    unit: 2,
    level: 100,
    semester: 2,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED152',
    title: 'History and Philosophy of Science',
    unit: 2,
    level: 100,
    semester: 2,
    department: 'Physics',
    prerequisites: [],
  },

  // ===== 200 LEVEL — FIRST SEMESTER (total 16) =====
  {
    courseCode: 'CHM101',
    title: 'General Chemistry I (Inorganic)',
    unit: 2,
    level: 200,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'EDU201',
    title: 'Curriculum Delivery and General Teaching Methods',
    unit: 2,
    level: 200,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'ENT211',
    title: 'Entrepreneurship and Innovation',
    unit: 2,
    level: 200,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'PHY211',
    title: 'Workshop Practice',
    unit: 2,
    level: 200,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED251',
    title: 'Introduction to Science Education',
    unit: 2,
    level: 200,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED175',
    title: 'Elementary Mechanics I',
    unit: 2,
    level: 200,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED171',
    title: 'History and Philosophy of Physics I',
    unit: 2,
    level: 200,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-EDU211',
    title: 'Human Learning and Instruction in Digital Age',
    unit: 2,
    level: 200,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },

  // ===== 200 LEVEL — SECOND SEMESTER (total 16) =====
  {
    courseCode: 'GST212',
    title: 'Philosophy, Logic and Human Existence',
    unit: 2,
    level: 200,
    semester: 2,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'CDS200',
    title: 'Career Development Studies',
    unit: 0,
    level: 200,
    semester: 2,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'PHY204',
    title: 'General Physics VI (Waves and Optics)',
    unit: 2,
    level: 200,
    semester: 2,
    department: 'Physics',
    prerequisites: ['PHY102'],
  },
  {
    courseCode: 'PHY202',
    title: 'Introduction to Electric Circuits and Electronics',
    unit: 2,
    level: 200,
    semester: 2,
    department: 'Physics',
    prerequisites: ['PHY102'],
  },
  {
    courseCode: 'NAU-EDU112',
    title: 'Introduction to Educational Psychology',
    unit: 2,
    level: 200,
    semester: 2,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-EDU216',
    title: 'Digital Technologies for Curriculum Delivery',
    unit: 2,
    level: 200,
    semester: 2,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED272',
    title: 'History and Philosophy of Physics II',
    unit: 2,
    level: 200,
    semester: 2,
    department: 'Physics',
    prerequisites: ['NAU-SED171'],
  },
  {
    courseCode: 'NAU-SED278',
    title: 'Geophysical System and Space Science',
    unit: 2,
    level: 200,
    semester: 2,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED176',
    title: 'Elementary Mechanics II',
    unit: 2,
    level: 200,
    semester: 2,
    department: 'Physics',
    prerequisites: ['NAU-SED175'],
  },

  // ===== 300 LEVEL — FIRST SEMESTER (total 15 after top-up) =====
  {
    courseCode: 'PHY205',
    title: 'Thermal Physics',
    unit: 3,
    level: 300,
    semester: 1,
    department: 'Physics',
    prerequisites: ['PHY102'],
  },
  {
    courseCode: 'PHY207',
    title: 'Practical Physics III',
    unit: 3,
    level: 300,
    semester: 1,
    department: 'Physics',
    prerequisites: ['PHY108'],
  }, // top-up 2 -> 3
  {
    courseCode: 'PHY201',
    title: 'General Physics II',
    unit: 2,
    level: 300,
    semester: 1,
    department: 'Physics',
    prerequisites: ['PHY102'],
  },
  {
    courseCode: 'NAU-SED271',
    title: 'Workshop Practice',
    unit: 2,
    level: 300,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'PHY301',
    title: 'Analytical Mechanics',
    unit: 3,
    level: 300,
    semester: 1,
    department: 'Physics',
    prerequisites: ['PHY102'],
  },
  {
    courseCode: 'NAU-SED351',
    title: 'Laboratory Organization and Management',
    unit: 2,
    level: 300,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },

  // ===== 300 LEVEL — SECOND SEMESTER (total 16) =====
  {
    courseCode: 'ENT312',
    title: 'Venture Creation',
    unit: 2,
    level: 300,
    semester: 2,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'GST312',
    title: 'Peace and Conflict Resolution',
    unit: 2,
    level: 300,
    semester: 2,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'PHY208',
    title: 'General Physics Practical',
    unit: 1,
    level: 300,
    semester: 2,
    department: 'Physics',
    prerequisites: ['PHY207'],
  },
  {
    courseCode: 'PHY306',
    title: 'Statistical and Thermal Physics',
    unit: 3,
    level: 300,
    semester: 2,
    department: 'Physics',
    prerequisites: ['PHY205'],
  },
  {
    courseCode: 'PHY206',
    title: 'General Physics VII (Energy and Environment)',
    unit: 2,
    level: 300,
    semester: 2,
    department: 'Physics',
    prerequisites: ['PHY204'],
  },
  {
    courseCode: 'NAU-EDU212',
    title: 'Micro Teaching Practice',
    unit: 2,
    level: 300,
    semester: 2,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED274',
    title: 'Radiation Protection',
    unit: 2,
    level: 300,
    semester: 2,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED276',
    title: 'General Physics Method I',
    unit: 2,
    level: 300,
    semester: 2,
    department: 'Physics',
    prerequisites: [],
  },

  // ===== 400 LEVEL — FIRST SEMESTER (total 15) — exempt from 15 min =====
  {
    courseCode: 'PHY303',
    title: 'Electromagnetism',
    unit: 3,
    level: 400,
    semester: 1,
    department: 'Physics',
    prerequisites: ['PHY202'],
  },
  {
    courseCode: 'PHY305',
    title: 'Quantum Physics',
    unit: 3,
    level: 400,
    semester: 1,
    department: 'Physics',
    prerequisites: ['PHY301'],
  },
  {
    courseCode: 'EDU302',
    title: 'Educational Measurements, Tests, Research Methods and Statistics',
    unit: 3,
    level: 400,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED353',
    title: 'Seminar, Grant and Project Writing in Science Education',
    unit: 2,
    level: 400,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-EDU335',
    title: 'Introduction to Special Needs Education',
    unit: 2,
    level: 400,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED471',
    title: 'Entrepreneurship in Physics Education',
    unit: 2,
    level: 400,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },

  // ===== 400 LEVEL — SECOND SEMESTER (total 3) — exempt (practicum) =====
  {
    courseCode: 'EDU326',
    title: 'Teaching Practice II',
    unit: 3,
    level: 400,
    semester: 2,
    department: 'Physics',
    prerequisites: [],
  },

  // ===== 500 LEVEL — FIRST SEMESTER (total 15) =====
  {
    courseCode: 'PHY403',
    title: 'Mathematical Methods in Physics I',
    unit: 3,
    level: 500,
    semester: 1,
    department: 'Physics',
    prerequisites: ['PHY301'],
  },
  {
    courseCode: 'PHY405',
    title: 'Physics Entrepreneurship',
    unit: 3,
    level: 500,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'PHY401',
    title: 'Quantum Mechanics I',
    unit: 3,
    level: 500,
    semester: 1,
    department: 'Physics',
    prerequisites: ['PHY305'],
  },
  {
    courseCode: 'NAU-SED451',
    title: 'Special Problems in Science Education',
    unit: 2,
    level: 500,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED463',
    title: 'Geophysical System and Space Science',
    unit: 2,
    level: 500,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED453',
    title: 'Integrating Science',
    unit: 2,
    level: 500,
    semester: 1,
    department: 'Physics',
    prerequisites: [],
  },

  // ===== 500 LEVEL — SECOND SEMESTER (total 18 after filling blank unit) =====
  {
    courseCode: 'EDU400',
    title: 'Project',
    unit: 3,
    level: 500,
    semester: 2,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'PHY304',
    title: 'Electromagnetic Waves and Optics',
    unit: 3,
    level: 500,
    semester: 2,
    department: 'Physics',
    prerequisites: ['PHY303'],
  },
  {
    courseCode: 'PHY402',
    title: 'Quantum Physics II',
    unit: 3,
    level: 500,
    semester: 2,
    department: 'Physics',
    prerequisites: ['PHY401'],
  }, // unit was blank in document, set to 3
  {
    courseCode: 'PHY404',
    title: 'Mathematical Methods in Physics II',
    unit: 3,
    level: 500,
    semester: 2,
    department: 'Physics',
    prerequisites: ['PHY403'],
  },
  {
    courseCode: 'CDS400',
    title: 'Career Development Studies',
    unit: 0,
    level: 500,
    semester: 2,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED452',
    title: 'Curriculum Development in Science Education',
    unit: 2,
    level: 500,
    semester: 2,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED476',
    title: 'Fundamentals of Nanotechnology',
    unit: 2,
    level: 500,
    semester: 2,
    department: 'Physics',
    prerequisites: [],
  },
  {
    courseCode: 'NAU-SED432',
    title: 'Computer and Society',
    unit: 2,
    level: 500,
    semester: 2,
    department: 'Physics',
    prerequisites: [],
  },
];

module.exports = physicsCourses;
